apiVersion: v1
kind: Service
metadata:
  name: cicd-app-service
  namespace: default
  labels:
    app: cicd-app
spec:
  selector:
    app: cicd-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP 